language: node_js
node_js:
  - 6
  - 7
install:
  - npm install -g codecov yarn
  - yarn
script:
  - yarn run lint
  - yarn run coverage
  - codecov
notifications:
  slack:
    rooms:
      secure: s5SDWFY9MpUUlOVozrcSW1SkP0PUNfyamUNrYVIHDF1u6NsD1pRDafk1dKUfkJq55jL7QiCoJfJ9PqY9WV6IJudOAztD5ZoK+gYZw7S8XvpwLeFccI4SF0lJi5n2o+IqLAm9/M/gHegzIypgIVk333kQCykTTNF7KceQQVHNMXzwW4xoHmxenM6BRtDW9Chvy3OfZbdqkJhgZsjnVOfKTc9lvO79TrtdnaawZGHOzLz0zMqYID9LCK4Bhe7qJZlPC/z58AXE59B3zE+gTqDx321p+Qupx+xcnImTmW5vAYZ2lH6B3dCLFWd6I6E8msnjrGDd3oCahhcy4oOOuKR/SSx1FV41D59aKcyzmdC7kB+W1nc2JSYbaPk4xWNug7PNWUlntwITQ9ppcKGCo7qdvDf2Ey3Ka7G9DJzJ/WoCIxp99zAp8/DBQRv1J8lqbqcXjvED+NYjCORTWZlIgXelu6d6m61PKwhocYYQszDPWFdZR4ECNyI+oKDBJASdCBMBevWldXUUYbrtTcePxmGGKyNqO1klvudjqICnofZGMv1inG9Fs5G2+tIYj+lmzOrL0FpsikNCDOPfFYHQQP2Fz+/DYYGJ97mHSE/f0EjwXezWA4s0kZKDIdccs9wM4WYomNF/zi1qhfdOnUNpL9UebGNzxSkuTHA4B2LXeFRcgnA=
